spring:
    profiles:
        active:
        - dev
---
spring:
    profiles:   dev
    application:
        name:   provider-1-dev
---
spring:
    profiles:   test
    application:
        name:   provider-1-test
 
# utf-8 保存
